### ISSUE TITLE
关于预处理文件的缺失

### ISSUE THREAD

**Issue by Tina217** [HduDBSI/GASM#1]
尊敬的作者您好，冒昧打扰了，请问预处理文件中lastfm_freq.py 文件中的第186行musicInfo = json.load(open(os.path.join(BASE_DIR,'lastfm_export_data/track_info.json')))，提到了一个track_info.json文件，我想自己走一遍预处理的过程，但是发现原始数据集中并没有提供，请问您方便提供一下吗？非常感谢！祝您生活愉快~

**Comment by hahahaHan233** [comment]
Lastfm export data- link: https://drive.google.com/file/d/1vIHw0alf2wLKqjQQLObnMeCBSqET1mti/view?usp=share_link
